In [1]:
from google.colab import files

uploaded = files.upload()

Saving Pakistan Largest Ecommerce Dataset.csv to Pakistan Largest Ecommerce Dataset.csv

In [2]:
import os

print(os.listdir('/content'))

['.config', 'Pakistan Largest Ecommerce Dataset.csv', 'sample_data']

In [3]:
import pandas as pd

df = pd.read_csv('/content/Pakistan Largest Ecommerce Dataset.csv')

df.head()

/tmp/ipykernel_1761/3715572289.py:3: DtypeWarning: Columns (1,2,3,7,8,9,11,12,13,14,17,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/Pakistan Largest Ecommerce Dataset.csv')

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,Month,Customer Since,M-Y,FY,Customer ID,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,211131.0,complete,7/1/2016,kreations_YI 06-L,1950.0,1.0,1950.0,100147443,Women's Fashion,\N,...,7.0,2016-7,7-2016,FY17,1.0,NaN,NaN,NaN,NaN,NaN
1,211133.0,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1.0,240.0,100147444,Beauty & Grooming,\N,...,7.0,2016-7,7-2016,FY17,2.0,NaN,NaN,NaN,NaN,NaN
2,211134.0,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.0,1.0,2450.0,100147445,Women's Fashion,\N,...,7.0,2016-7,7-2016,FY17,3.0,NaN,NaN,NaN,NaN,NaN
3,211135.0,complete,7/1/2016,kcc_krone deal,360.0,1.0,60.0,100147446,Beauty & Grooming,R-FSD-52352,...,7.0,2016-7,7-2016,FY17,4.0,NaN,NaN,NaN,NaN,NaN
4,211136.0,order_refunded,7/1/2016,BK7010400AG,555.0,2.0,1110.0,100147447,Soghaat,\N,...,7.0,2016-7,7-2016,FY17,5.0,NaN,NaN,NaN,NaN,NaN

In [4]:
df.shape

(1048575, 26)

In [5]:
df.columns

Index(['item_id', 'status', 'created_at', 'sku', 'price', 'qty_ordered',
       'grand_total', 'increment_id', 'category_name_1',
       'sales_commission_code', 'discount_amount', 'payment_method',
       'Working Date', 'BI Status', ' MV ', 'Year', 'Month', 'Customer Since',
       'M-Y', 'FY', 'Customer ID', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 26 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   item_id                584524 non-null  float64
 1   status                 584509 non-null  object
 2   created_at             584524 non-null  object
 3   sku                    584504 non-null  object
 4   price                  584524 non-null  float64
 5   qty_ordered            584524 non-null  float64
 6   grand_total            584524 non-null  float64
 7   increment_id           584524 non-null  object
 8   category_name_1        584360 non-null  object
 9   sales_commission_code  447346 non-null  object
 10  discount_amount        584524 non-null  float64
 11  payment_method         584524 non-null  object
 12  Working Date           584524 non-null  object
 13  BI Status              584524 non-null  object
 14   MV                    584524 non-null  object
 15  Year                   584524 non-null  float64
 16  Month                  584524 non-null  float64
 17  Customer Since         584513 non-null  object
 18  M-Y                    584524 non-null  object
 19  FY                     584524 non-null  object
 20  Customer ID            584513 non-null  float64
 21  Unnamed: 21            0 non-null       float64
 22  Unnamed: 22            0 non-null       float64
 23  Unnamed: 23            0 non-null       float64
 24  Unnamed: 24            0 non-null       float64
 25  Unnamed: 25            0 non-null       float64
dtypes: float64(13), object(13)
memory usage: 208.0+ MB

In [7]:
missing_values = df.isnull().sum()

print(missing_values)

item_id                   464051
status                    464066
created_at                464051
sku                       464071
price                     464051
qty_ordered               464051
grand_total               464051
increment_id              464051
category_name_1           464215
sales_commission_code     601229
discount_amount           464051
payment_method            464051
Working Date              464051
BI Status                 464051
 MV                       464051
Year                      464051
Month                     464051
Customer Since            464062
M-Y                       464051
FY                        464051
Customer ID               464062
Unnamed: 21              1048575
Unnamed: 22              1048575
Unnamed: 23              1048575
Unnamed: 24              1048575
Unnamed: 25              1048575
dtype: int64

In [8]:
df = df.dropna(how='all')

print("Dataset shape after removing empty rows:", df.shape)

Dataset shape after removing empty rows: (584524, 26)

In [9]:
df = df.dropna(axis=1, how='all')

print("Shape after removing empty columns:", df.shape)

Shape after removing empty columns: (584524, 21)

In [10]:
duplicate_count = df.duplicated().sum()

print("Total duplicate rows:", duplicate_count)

Total duplicate rows: 0

In [11]:
missing_percent = (df.isnull().sum() / len(df)) * 100

print(missing_percent.sort_values(ascending=False))

sales_commission_code    23.468326
category_name_1           0.028057
sku                       0.003422
status                    0.002566
Customer Since            0.001882
Customer ID               0.001882
price                     0.000000
item_id                   0.000000
created_at                0.000000
increment_id              0.000000
discount_amount           0.000000
grand_total               0.000000
qty_ordered               0.000000
Working Date              0.000000
payment_method            0.000000
BI Status                 0.000000
 MV                       0.000000
Month                     0.000000
Year                      0.000000
M-Y                       0.000000
FY                        0.000000
dtype: float64

In [12]:
df['sales_commission_code'] = df['sales_commission_code'].fillna('Unknown')

df = df.dropna(subset=[
    'category_name_1',
    'sku',
    'status',
    'Customer Since',
    'Customer ID'
])

print(df.isnull().sum())

item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64

In [13]:
df['created_at'] = pd.to_datetime(
    df['created_at'], errors='coerce'
)

print(df['created_at'].dtype)

datetime64[ns]

In [14]:
df['Order_Month'] = df['created_at'].dt.month
df['Order_Year'] = df['created_at'].dt.year

df[['created_at', 'Order_Month', 'Order_Year']].head()

  created_at  Order_Month  Order_Year
0 2016-07-01            7        2016
1 2016-07-01            7        2016
2 2016-07-01            7        2016
3 2016-07-01            7        2016
4 2016-07-01            7        2016

In [15]:
df['Order_Month'] = df['created_at'].dt.month
df['Order_Year'] = df['created_at'].dt.year

df[['created_at', 'Order_Month', 'Order_Year']].head()

  created_at  Order_Month  Order_Year
0 2016-07-01            7        2016
1 2016-07-01            7        2016
2 2016-07-01            7        2016
3 2016-07-01            7        2016
4 2016-07-01            7        2016

In [16]:
df['Total_Sales'] = df['price'] * df['qty_ordered']

df[['price', 'qty_ordered', 'Total_Sales']].head()

    price  qty_ordered  Total_Sales
0  1950.0          1.0       1950.0
1   240.0          1.0        240.0
2  2450.0          1.0       2450.0
3   360.0          1.0        360.0
4   555.0          2.0       1110.0

In [17]:
import numpy as np

df['Discount_Percentage'] = (
    df['discount_amount'] /
    df['Total_Sales'].replace(0, np.nan)
) * 100

df[['discount_amount', 'Total_Sales',
    'Discount_Percentage']].head()

   discount_amount  Total_Sales  Discount_Percentage
0              0.0       1950.0             0.000000
1              0.0        240.0             0.000000
2              0.0       2450.0             0.000000
3            300.0        360.0            83.333333
4              0.0       1110.0             0.000000

In [18]:
df['Customer_Lifetime_Value'] = (
    df.groupby('Customer ID')['Total_Sales']
    .transform('sum')
)

df[['Customer ID', 'Total_Sales',
    'Customer_Lifetime_Value']].head()

   Customer ID  Total_Sales  Customer_Lifetime_Value
0          1.0       1950.0                   1950.0
1          2.0        240.0                    510.0
2          3.0       2450.0                   3695.0
3          4.0        360.0                2748846.5
4          5.0       1110.0                   1110.0

In [19]:
print("Dataset Shape:", df.shape)

print("\nNew Features:")
print(df[['Order_Month',
          'Order_Year',
          'Total_Sales',
          'Discount_Percentage',
          'Customer_Lifetime_Value']].head())

Dataset Shape: (584314, 26)

New Features:
   Order_Month  Order_Year  Total_Sales  Discount_Percentage  \
0            7        2016       1950.0             0.000000
1            7        2016        240.0             0.000000
2            7        2016       2450.0             0.000000
3            7        2016        360.0            83.333333
4            7        2016       1110.0             0.000000

   Customer_Lifetime_Value
0                   1950.0
1                    510.0
2                   3695.0
3                2748846.5
4                   1110.0

In [20]:
df.to_csv('Pakistan_Ecommerce_Cleaned.csv', index=False)

print("Dataset saved successfully!")

Dataset saved successfully!

In [21]:
from google.colab import files

files.download('Pakistan_Ecommerce_Cleaned.csv')